### ISSUE TITLE
State size 59 vs 58 error

### ISSUE THREAD

**Issue by liyuanl6666** [mhauskn/dqn-hfo#25]
Hi, 
I tried he code and it work well on one of my machine; but for a new server with ubuntu 14.04, it shows the following strange error: the state size is 59, while it should be 58.
Can you enlight me why this could happen?

Detailed error log:
...
Launch npc base_right-2
Launch npc base_right-3
Launch npc base_right-4
Launch npc base_right-5
Launch npc base_right-6
Launch npc base_right-7
base_left 11: [0, 7]  see synch.
Launch npc base_right-8
Launch npc base_right-9
Launch npc base_right-10
Launch npc base_right-11
Checking all players connected
Starting game
F0823 00:37:30.385576  2669 dqn_main.cpp:110] Check failed: current_state.size()                                                 == dqn.state_size() (59 vs. 58)
*** Check failure stack trace: ***
    @     0x7f4619803dbd  google::LogMessage::Fail()
    @     0x7f4619805c5d  google::LogMessage::SendToLog()
    @     0x7f46198039ac  google::LogMessage::Flush()
    @     0x7f461980657e  google::LogMessageFatal::~LogMessageFatal()
    @           0x453f89  PlayOneEpisode()
    @           0x455479  KeepPlayingGames()
    @           0x4568df  std::thread::_Impl<>::_M_run()
    @     0x7f461826ea60  (unknown)
    @     0x7f46192e0184  start_thread
    @     0x7f46179d637d  (unknown)
Aborted (core dumped)

**Comment by mhauskn** [comment]
There has recently been the addition of 1 feature to the state space of
HFO, so the DQN code will likely need to be updated to work with the larger
state space.

**Comment by wbwatkinson** [comment]
If I understand the particular issue, it is the adding of action_status, a flag which indicates whether the agent's last action was successfully registered with the agent's action effector or not (but not necessarily if that action was successfully executed by the server), in HFO that causes the state size check to fail. action_status is the 59th feature of the low level feature state space.

I'm exploring a modification to the DQN code, but I would think that using a commit of HFO prior to 59c57e8 would work. Has anyone tried this? It would seem [5df1cd1](https://github.com/LARG/HFO/tree/5df1cd170092f317353091ea69feab36cd23d3ce) might be a reasonable choice.

**Comment by drallensmith** [comment]
It would appear that checks for number of features should check for a
minimum number of features.

-Allen

**Comment by drallensmith** [comment]
I have been thinking that it would be advisable to implement an interface
for changing possible settings on HFO, such as whether extra features are
in the set, what MaxHFODist (or similar) was used, etc. This could assist
with compatibility issues such as the above.

BTW, I am guessing that the dqn-hfo code was updated for the unum (uniform
number) added features?

-Allen

**Comment by wbwatkinson** [comment]
I confirmed that using commit [5df1cd1](https://github.com/LARG/HFO/tree/5df1cd170092f317353091ea69feab36cd23d3ce) of HFO works with the current version, [eb22d7a](https://github.com/mhauskn/dqn-hfo/commit/eb22d7a63d71ff6a18af1cc22b65353ebda5358c), of dqn-hfo. These were the specific steps I took:

1. First install the correct version of Caffe: 
2. `git clone https://github.com/BVLC/caffe.git`
3. `cd caffe && git checkout 2ef584785c8ade90260eb117f189146364494183`
4. Apply the changes to solver listed above
5. Follow installation instructions at https://github.com/BVLC/caffe
6. Next install HFO:
7. `git clone https://github.com/LARG/HFO.git`
8. `cd HFO && git checkout 5df1cd1` - this is the key change to the instructions posted on the README.md
9. Follow installation instructions at https://github.com/LARG/HFO
10. Now we are ready to install dqn-hfo:
11. `git clone https://github.com/mhauskn/dqn-hfo.git`
12. `cd dqn-hfo && mkdir build && cd build`
13. `cmake -DCMAKE_BUILD_TYPE=Release -DCAFFE_ROOT_DIR=/u/mhauskn/projects/caffe/ -DHFO_ROOT_DIR=/u/mhauskn/projects/HFO/ ..` You will have to change the paths to point to your installation of caffe and HFO
14. `make -j4`
15. Run a test job: `mkdir state && ./bin/dqn -save state/test -alsologtostderr`

If I update dqn-hfo to work with the extended low-level feature set, I'll post an update, but as my research doesn't depend on the last action possible state flag, it may be a while.

**Comment by mhauskn** [comment]
Hopefully addressed in #28
