### ISSUE TITLE
Shortcuts for visualization?

### ISSUE THREAD

**Issue by abhisheknaik96** [mhauskn/dqn-hfo#31]
1. Since my server doesn't support X11 display forwarding, is there an easier way to visualize the learnt policies than having the copy the rcg logs to my local machine and rendering the screenshots via the HFO GUI?

2. Is there a shortcut to visualize the policies while the training takes place? I would really like an alternative to having to wait till the end of a run to check out what kind of policy is being learnt (apart from the messy way of saving checkpoints at frequent intervals and then performing (1) above?

**Comment by mhauskn** [comment]
1. If you have ffmpeg you may be able to use [this script](https://github.com/LARG/HFO/blob/master/bin/record_video.sh) to convert it to mp4 on the server and copy that to your local machine.

2. Not really. However, you could automate the process of 1) saving checkpoints 2) running an evaulation of the saved checkpoint to create an rcg file 3) making that rcg into a mp4.

**Comment by abhisheknaik96** [comment]
Great, will try installing ffmpeg on my server. Thanks!
