### ISSUE TITLE
reproduce problem: env is running!

### ISSUE THREAD

**Issue by wwxFromTju** [mhauskn/dqn-hfo#32]
Dear mhauskn:

  I want to use tensorflow to reproduce this experiment. But I find some problem.The most import is agent and env use network to connect, so when I training the policy, the env is runing! And when I use network to infer the action(need some time to cal), but the env is also runing!

  so how to control the env waiting the agent?

Thx!

**Comment by mhauskn** [comment]
The environment should wait for the agent to choose its next action. There
is a flag --no-sync which disables this and requires the agents to make
decisions in real time. Make sure that you don't run the simulator with
this flag.

**Comment by wwxFromTju** [comment]
Hi, when I want to look this effect, I find the simulator isn't run, but I can get some log in term.

such as: I run my code, agent is stop in the simulator, but I can get diff log (I print the state info, action and so on), what happen?

**Comment by wwxFromTju** [comment]
maybe render module have some issue, other module is fine.
