### ISSUE TITLE
Update method

### ISSUE THREAD

**Issue by StephanieDU** [mhauskn/dqn-hfo#34]
I am not familiar with Caffe..So can anyone help me to understand the update of this parameterized action method? Is it still the same as the standard DDPG update or the gradients of critic is calculated in two part: with respect to discrete action and parameters separately? If the gradients is in two part, then how to update the actor network? 
Thanks in advance!

**Comment by mhauskn** [comment]
Gradients are computed for discrete actions here https://github.com/mhauskn/dqn-hfo/blob/master/src/dqn.cpp#L924 and for continuous parameters in the next line. They are applied to the respective parts of the actor network and backpropagated to update the actor's weights.

**Comment by StephanieDU** [comment]
Thanks for prompt reply! So basically this means you need to backpropagate twice to update the actor network? Am I right? Since most of the weights of actor network is shared between discrete and continuous action, will this kind of backpropagation work well?

**Comment by mhauskn** [comment]
Actually it uses a single backpropagation which happens here: https://github.com/mhauskn/dqn-hfo/blob/master/src/dqn.cpp#L963

The gradients for the discrete and continuous parts of the actor network are passed to the respective output layers on the actor network and backpropagated once.

**Comment by StephanieDU** [comment]
Thanks for your detailed explanation! I will close this issue.
